{% set name = "openfoam" %}
{% set version = "2412" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://develop.openfoam.com/Development/openfoam/-/archive/OpenFOAM-v{{ version }}/openfoam-OpenFOAM-v{{ version }}.tar.gz
  sha256: 27d06edb4a6ffc6f88a494edd3b289d5d0a0874866a416b6b0d0a26aba2d9c4a

build:
  skip: True  # [not linux]
  number: 0
  rpaths:
    - lib/
    - lib/sys-mpich/
    - lib/dummy/

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - make  # [unix]
    - m2w64-make  # [win]
    - cmake
    - mpich
  host:
    - scotch
    - ptscotch
    - zoltan
    - kahip
    - mpich    
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cgal
    - fftw
    - mpfr
    - ncurses
    - parmetis
    - petsc
    - hypre
    - flex  # [unix]
    - m2-flex  # [win]
    - zlib    
  run:
    - metis

test:
  commands:
    - test -f ${PREFIX}/lib/libOpenFOAM.so  # [linux]
    - test -f ${PREFIX}/bin/blockMesh  # [linux]    
    - ${PREFIX}/bin/foamTestTutorial -full incompressible/simpleFoam/pitzDaily

about:
  home: https://openfoam.com/
  summary: OpenFOAM-{{ version }}
  description: |
    OpenFOAM is a free, open source computational fluid dynamics (CFD) 
    software package released by the ESI.
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://www.openfoam.com/documentation/overview
  dev_url: https://www.openfoam.com/download/openfoam-repositories

extra:
  recipe-maintainers:
    - ldallolio
    - daviddanan
